### ISSUE TITLE
app armor ERROR 

### ISSUE THREAD

**Issue by denisght71** [DoliCloud/SellYourSaas#104]
Hello,
When I configure AppArmor I get the error:
ERROR: Found reference to variable HOME, but is never declared

**Comment by eldy** [comment]
When running which command do you have this ?

**Comment by eldy** [comment]
Are you on ubuntu ?  You probably miss the file /etc/apparmor.d/tunables/home
that is provided by package   apparmor

**Comment by eldy** [comment]
Closed as i can't reproduce on ubuntu 18.04 neither 20.04
