### ISSUE TITLE
Test jailkit

### ISSUE THREAD

**Issue by eldy** [DoliCloud/SellYourSaas#146]

**Comment by hregis** [comment]
@eldy hello, what is the problem ?

**Comment by eldy** [comment]
@hregis 
Ticket was created to be assigned to @GurvanKervern (he works at DoliCloud) to test and install it on our test env.

**Comment by GurvanKervern** [comment]
I edited the title to reflect the task : evaluate how useful would be jailkit and how problematic it would be to integrate with other tools on our current platform.

**Comment by eldy** [comment]
Test/use of jailkit has been abandonned
