### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by karozans** [DoliCloud/SellYourSaas#160]
**Describe the bug**
I am running through the setup procedures now and am having problems.  Especially on the DNS steps.  I am running my installation on Amazon AWS servers, and am really having a difficult time.  I need to get this install ASAP for a demo, and it's not going great.

**To Reproduce**
1.  Following installation directions.

**Expected behavior**
Documentation is pretty good start, but there are several places where I am unsure of if I am supposed to be doing the configuration steps on the master or the deploy servers.

It would also be nice if there was a brief summary at the beginning of each section telling the overview of what you are doing and why as well as making it painfully obvious which server you are supposed to be doing this on.  There are several sections that do make a distinction, but some that don't.  I would suggest adding color coding to titles in each section that says...

All Servers
Master Server
Deployment Server

If there is nothing to be done for the master server for let's say "Creating a Working Directory", you could simply put "N/A" for the "Master Server and under "All Servers".  This way the directions are uniform and really obvious on which server you are supposed to be working on.

The DNS section seems a bit confusing and I cannot get the DNS to work.

Uniform colorization of title headers and such would be nice.

Another thing that would be nice is having setup instructions for someone using cPanel or Plesk.  Using these things is pretty common.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by eldy** [comment]
We made a lot of enhancement to doc since your ticket. However, your ticket is too large to provide a real answer. So if despite then enehancement to doc, you still have question, it will be better to create 1 ticket per question so we will be able to answer to each point and modify the documentation to make it clearer...
