### ISSUE TITLE
Error creating client instance: "connection refused"

### ISSUE THREAD

**Issue by sun2dayo** [DoliCloud/SellYourSaas#198]
### Discussed in https://github.com/DoliCloud/SellYourSaas/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **sun2dayo** March  5, 2022</sup>
hello great team
I need your help to overcome this challenge.
When trying to create a client instance, I get the error " connection refused" as you can see in the screenshot.
So the instance creation process is not 100% complete.
![Registration-dolisig-basic-](https://user-images.githubusercontent.com/95107558/156901722-54f403a5-89d9-48fe-9f9a-15cf2dacaf35.png)
But I was able to verify that the client instance is created successfully (if I enter directly into the url created for the client, I can connect to the client instance dolibarr application (using the username and password initially set in the 'dump file'). Application of the client instance I see that everything seems to be perfect.
I checked the /var/log/remote_server.log and the whole deployment process happens without any errors.

I believe that something happens during the deployment process, that is, in the step right after the "shell after" execution and that stops the process, before automatically forwarding the client to the dashborad.

One of the things that I could verify, is that any variable or sql statement configured "sql after" in the package is not applied.

Where can I be failing?</div>

**Comment by eldy** [comment]
So the probleme here is that the master is not able to connect to the customer instance by a direct sql access. Check to make a connection from the master tobthe deployment dbn... using the login dbu... and the dns name that appears in message.
May be a firewall port is blocked. Enable log module on the master, and check into log file (there is one log dedicated for the myaccount area) to see the user used and try to connect from master using this user. You reach the end...

**Comment by sun2dayo** [comment]
Hi @eldy 
Thank you very much... very helpful.
