### ISSUE TITLE
sellyoursaas can work in a dolibarr installation installed in cpanel.

### ISSUE THREAD

**Issue by Wotan6891** [DoliCloud/SellYourSaas#199]
hello,

sellyoursaas can work in a dolibarr installation installed in cpanel.

Could I install it as another module?

**Comment by Wotan6891** [comment]
![Captura de Pantalla 2022-03-18 a la(s) 18 30 52](https://user-images.githubusercontent.com/29691466/159096856-066396e8-4de6-4254-8247-b75b851b9531.png)
![Captura de Pantalla 2022-03-18 a la(s) 18 31 01](https://user-images.githubusercontent.com/29691466/159096866-30af91f2-96c1-47ea-a04c-c641e9950be1.png)

---------------------------------------------------------------------
I managed to install it from the file manager, in the custom folder.

the module activates it, and the interface looks fine.

but this problem happens when I want to create a "NewPackages" or when I click on "NewInstance" 

Error message: 

Access to a page that needs a token (constant CSRFCHECK_WITH_TOKEN is defined) is refused by CSRF protection in main.inc.php. Token not provided.

**Comment by hregis** [comment]
@Wotan6891 can you try with develop branch of Dolibarr ?

**Comment by Wotan6891** [comment]
> @ Wotan6891 ¿puedes probar con la rama de desarrollo de Dolibarr?

Hello,

You mean if I can install a server from scratch like this in your sellyoursaas documentation?

If that's the question, I still can't.

I'm only using cpanel right now. and I don't have root access.

**Comment by eldy** [comment]
The goal of sellyoursaas is to provide a full solution (applicative but also system).
It replaces completely cpanel. And you need root to install it because goal is also to replace cpanel and any other system tools.
You must have a full control of your server.
