### ISSUE TITLE
Taille des HDD

### ISSUE THREAD

**Issue by wouam31200** [DoliCloud/SellYourSaas#206]
Bonjour, je trouve le projet super!
Et je pense à créer deux serveurs.

J'ai une question par rapport à l'ajout des disques :
Les B2-15 ont déjà 15Go + 250Mo par instance. Donc 125Go pour 500 instances (si je ne me trompe pas)

Les 15Go vont être pour l'installation de SellYourSaas ou du coup ils sont perdus ?

Merci

**Comment by eldy** [comment]
Tout depend. Si vous installer un disque dur pour le stockage home des instances, les go du disque systeme seront en effet peu utilisé. Car seule la base de sonnée se trouve dans le disque system. Les rep et fichiers de chaque instance sera sur le disque non systeme. Il est aussi possible de deplacer lz /var/lib/mysql sur le disque non systeme egalement, auquel cas les go du disque systeme ne serviront a rien.

**Comment by wouam31200** [comment]
Merci beaucoup
