### ISSUE TITLE
 Data too long for column 'ext_payment_id' at row 1 ,

### ISSUE THREAD

**Issue by rycks** [DoliCloud/SellYourSaas#217]
**Describe the bug**
Return from stripe payment (test mode) : 

```
Success to charge card (pi_3L8JqLHU6nqAr7bd0YGuXWKq with pk_test_51Ks45eHU6nqAr7bd3mFZKVBOmbYOBzo61HkZjxlPMa6nbAmpzkkGyt35mGm99FtQwiiY2RP27xfCc2tQfGmCxWZR0057qOFe38),
Data too long for column 'ext_payment_id' at row 1 ,
Email sent to thirdparty (to xxx@xxxx without any attached document, language = fr_FR)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/1468823/172567054-1cc29ee8-2ca8-4c78-b256-0d559c09d8eb.png)

![image](https://user-images.githubusercontent.com/1468823/172567124-fd1d448b-47f3-4923-96d8-64a13942803e.png)

"my" solution was to change in sellyoursaasutils.class.php line 1236

```
$paiement->ext_payment_id = $charge->id.':'.$customer->id.'@'.$stripearrayofkeys['publishable_key'];
```

to

```
$paiement->ext_payment_id = $charge->id;//.':'.$customer->id.'@'.$stripearrayofkeys['publishable_key'];
```

**Comment by eldy** [comment]
In v16, field is now 255.
A better fix would be to make 
$paiement->ext_payment_id = dol_trunc($charge->id.':'.$customer->id.'@'.$stripearrayofkeys['publishable_key'], 250);
So we keep max of information.
