### ISSUE TITLE
myaccount.sellmysaas.com - "child died with signal 11"

### ISSUE THREAD

**Issue by priojk** [DoliCloud/SellYourSaas#230]
Since a while I am trying to replicate the SellYorSaaS setup from the ground up on **Ubuntu 20.04** hosted in the **public cloud of OVH**. I think I am now almost there, admin and myaccount pages are generally operational and I did successfully set up instances on the deployment server.

I will give feedback into the documentation as pull requests once I have a bit of time (apart from the fact that this is an excellent and very detailed example of great instructions) - there are some points, where I needed to slightly deviate from the written "truth".

**One of the last points where I am struggling are some sub-pages on the myaccount page:**

If I click on **"my apps and options"** or **"add payment mode"** nothing is shown apart from the **error ERR_EMPTY_RESPONSE**. 

The apache error log shows: 
`[Tue Jul 19 18:53:48.485111 2022] [mpm_itk:error] [pid 634120] child died with signal 11`

The last meaningful rows in the dolibar.log before the crash are:
```
2022-07-19 19:11:28 DEBUG   84.189.75.1     sql=SELECT DISTINCT r.module, r.perms, r.subperms FROM llx_usergroup_rights as gr, llx_usergroup_user as gu, llx_rights_def as r WHERE r.id = gr.fk_id AND gr.entity = 1 AND gu.entity IN (0,1) AND r.entity = 1 AND gr.fk_usergroup = gu.fk_usergroup AND gu.fk_user = 2 AND r.perms IS NOT NULL
2022-07-19 19:11:28 NOTICE  84.189.75.1     --- Access to GET /index.php - action=, massaction=
2022-07-19 19:11:28 DEBUG   84.189.75.1     sql=SELECT transkey, transvalue FROM llx_overwrite_trans where lang='de_DE' OR lang IS NULL AND entity IN (0, 1) ORDER BY lang DESC
```

Everything else under myaccount works as expected (show/modify account, show invoices etc.).

Furthermore, I am sure that I have seen the now non-working pages after the creation of the first instance. So some later data leads probably to a crash in whatever sub task is called to fetch some data.

I am a bit stuck here regarding further debugging and any hint would be much appreciated. It may well be a configuration error from my side rather than a real bug.

**Comment by sun2dayo** [comment]
Hello
I have encountered the same issue. when I click on "my apps and options" or "add payment mode" nothing is shown apart from the error ERR_EMPTY_RESPONSE. But this happens when the associated instance is in the Deployment status "processing" or "done" . But when they are in "undeployed" mode the links are accessible without any error.

**Comment by priojk** [comment]
While investigating the issue further, I can confirm what @sun2dayo stated:

If an instance is undeployed, the myaccount pages "my apps and options" and "add payment mode" both are accessible. If the instance is deployed or re-deployed, an error page gets shown after a while - I guess, some timeout is involved here.

Since I am not the only one with this behaviour, I think it's safe to exclude a simple configuration error during the setup of the system.

While in Chrome, the error in the browser is stated as ERR_EMPTY_RESPONSE, in Firefox the error message says that no secure connection could get established. - Summing this up, I think a connection fails, something times out, a process crashes and the mentioned error message is shown.

While trying to debug this with some dol_syslog-messages, I noticed that from the myaccount page (.../custom/sellyoursaas/myaccount/index.php), no data is written into dolibarr.log after calling dol_syslog (logging is of course enabled and I checked for correct log level).  However, the logging in general is working and the log is getting filled while using SellYourSaaS - just not with the messages from the myaccount page.

So I am still not sure what exactly is going on here and why the call to the aforementioned pages fails.

**Comment by pandywibowo** [comment]
hello @sun2dayo  and @priojk,  
I have try to deploy with following the documentation and success. your problem can be solve with disable ssh2_disconnect() by setting constant SELLYOURSAAS_SSH2_DISCONNECT_DISABLED to 1 

cheers.
Pandi

**Comment by priojk** [comment]
Thank you so much! This was indeed the solution.

**Comment by sun2dayo** [comment]
Hi @pandywibowo 
Thanks so much.
Well, @priojk , luckily this was indeed the solution.
