### ISSUE TITLE
the certbot  

### ISSUE THREAD

**Issue by mstoluca** [DoliCloud/SellYourSaas#239]
input

domain= my domain real

certbot certonly -n --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --manual --preferred-challenges=dns --manual-auth-hook /home/admin/wwwroot/dolibarr_sellyoursaas/scripts/letsencrypt_authenticator.sh -d "*.withX.domain.com,withX.domain.com" -m mstoluca@gmail.com --deploy-hook "systemctl restart apache2"

output

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: withx.domain.com
  Type:   unauthorized
  Detail: Incorrect TXT record "oitD_Tswcf8fGgU_w_ggET1iHNFrb076-Kgjrz3b2F85Yp6jgjCIO8" found at _acme-challenge.withx.domain.com

  Domain: withx.domain.com
  Type:   unauthorized
  Detail: Incorrect TXT record "oitD_TNwcf8fGgU_w_ggET1iHNFrb076-Kgjrz3b2F85Yp6jgjCIO8" found at _acme-challenge.withx.domain.com

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
root@saas:/etc/apache2/sellyoursaas-enabled# 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mstoluca** [comment]
ya he cambiado los dns varias veces como dice acme, espero la propagacion y despues de 4 -8 hrs nada  me manda el mismo

**Comment by eldy** [comment]
If you ping withX.domain.com , do you get the ip of your deployment server ?

**Comment by erwinpalma** [comment]
I had the same Error, but my server is located in Hetzner, this provides has a free DNS service (like NOIP, DynDns, etc), and I have 
 located there my domain.

And I followed this tutorial.

https://github.com/hetzneronline/community-content/blob/master/tutorials/letsencrypt-dns/01.en.md

**Comment by erwinpalma** [comment]
@mstoluca 

¿Ya revisaste los logs?

¿Ya has solucionado el problema?

-----

have you checked the logs?
have you solved the issue?

**Comment by eldy** [comment]
Some changes were done into the hook /home/admin/wwwroot/dolibarr_sellyoursaas/scripts/letsencrypt_authenticator.sh
Do you still have trouble ?
