### ISSUE TITLE
Missing columns after upgrading the master branch of the sellyoursaas module

### ISSUE THREAD

**Issue by atm-florianm** [DoliCloud/SellYourSaas#240]
**Describe the bug**
After upgrading sellyoursaas to the latest commit (at the time of the problem it was 19afda2479f7878563d7fb92c0c74b4536579aee) on the master branch **and** disabling / re-enabling the module, some required columns are not created (namely the `comment` column in the `llx_sellyoursaas_whitelistip` and `llx_sellyoursaas_blacklistip` tables.

**To Reproduce**
It is not easy to reproduce because you need a fully set-up but slightly out-of-date sellyoursaas service.
1) `git pull origin master` in the module directory
2) try creating a free instance (any package / formula) → a blank page is shown with the following message:
   > Erreur: failed to get blacklistip elements

**Expected behavior**
The instance is created and the page is redirected to show the summary of the new instance (user name, password, host)

**Additional context**
I created the columns manually and I haven't detected any other problems since.

**Comment by hregis** [comment]
@atm-florianm restart dolibarr install for update database after sellyoursaas module update, it will reload the "sql/dolibarr_allversions.sql" file from sellyoursaas

**Comment by eldy** [comment]
Sellyoursaas works on rolling release for the moment. So there is no migration process from x to y.
Just 1 script to migrate whatever is the source version  dolibarr_allversions.sql
