### ISSUE TITLE
Fail2Ban: Not found any log file

### ISSUE THREAD

**Issue by QBoulanger** [DoliCloud/SellYourSaas#285]
**Describe the bug**
When following precisely the documentation for installing SellYourSaas. I got an issue when configuring fail2ban. 
Running 
```
systemctl status fail2ban
```
I get: 
```
Feb 15 05:50:06 admin systemd[1]: Starting Fail2Ban Service...

Feb 15 05:50:06 admin systemd[1]: Started Fail2Ban Service.

Feb 15 05:50:06 admin fail2ban-server[67812]: 2023-02-15 05:50:06,498 fail2ban                [67812]: ERROR   Failed during configuration: Have not found any log file for xinetd-fail jail

Feb 15 05:50:06 admin fail2ban-server[67812]: 2023-02-15 05:50:06,502 fail2ban                [67812]: ERROR   Async configuration of server failed

Feb 15 05:50:06 admin systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION

Feb 15 05:50:06 admin systemd[1]: fail2ban.service: Failed with result 'exit-code'.
```

I ran:

```
grep logpath /etc/fail2ban/jail.local | cut -d= -f2 | grep '^ /'|sort|uniq|xargs touch"
```
But it doesn't fixe the issue as no logpath is configured in jail.local for xinetd-fail. 

Looking for a solution, i tried changing backend=auto to backend=systemd (that allows having no logpath)
It works but I fear there might have problems using systemd instead of the advise backend.

**To Reproduce**
Follow the documentation for fail2Ban (https://github.com/DoliCloud/SellYourSaas/blob/2.0/doc/Documentation%20SellYourSaas%20-%20Master%20and%20Deployment%20Servers%20-%20EN.asciidoc#installation-of-fail2ban)

**Expected behavior**
fail2Ban successful start

**Desktop :**
 - OS: Ubuntu 20.04

**Comment by eldy** [comment]
May be you can try to remove the line

[xinetd-fail]
enabled = true

inside the jail.local

**Comment by QBoulanger** [comment]
Thanks a lot @eldy for your responses. As I was waiting for these, I set the implementation in standby. I'm going to resume it in the following days and I'll let you know on the results.
