### ISSUE TITLE
Issue when following documentation instructions on the installation of Logrotate

### ISSUE THREAD

**Issue by QBoulanger** [DoliCloud/SellYourSaas#287]
When following the installation instructions, i got the following error when installing Logrotate:
Running;
```
logrotate -f logrotate_admin_log
```
the error:
```
error: stat of /home/*/logs/*log failed: No such file or directory
```

Logrotate apparently does not support the " * " in the path written in  /etc/logrotate.d/logrotate_admin_log

I simply followed the documentation instructions.

I'm running on Ubuntu 20.04.

Thanks a lot for your help,

**Comment by eldy** [comment]
The * should be supported but may be you don't have any log file yet.
This happen on the master or on a deployment server ?

**Comment by eldy** [comment]
Install doc has been updated to create an empty log file if not exists so we are sur to not get the error

**Comment by QBoulanger** [comment]
@eldy Thank you very much. Hasn't had the time to test it yet. But i will.
