### ISSUE TITLE
Reloading the module shouldn't delete associated mail templates

### ISSUE THREAD

**Issue by atm-florianm** [DoliCloud/SellYourSaas#303]
**Summary**
Currently, when you restart SellYourSaas (for instance after upgrading it), you lose any customizations you made to the module's mail templates (fortunately, the daily SQL dump can save us).

**To Reproduce**
1. Go to Home > Setup > Emails > Email templates
2. Modify a mail template, for instance *InstanceDeployed* 
3. Disable SellYourSaas, then enable it again
4. Go back to Home > Setup > Emails > Email templates, scroll to *InstanceDeployed* (for instance)
5. The modifications you made are lost

**Expected behavior**
Enabling the module should not delete (or reset) previous customizations made in the module, including e-mail templates.

**Comment by eldy** [comment]
Fixed by #310
