### ISSUE TITLE
domain with 2 sufixes returns com.mx instead myfirma.com.mx

### ISSUE THREAD

**Issue by erwinpalma** [DoliCloud/SellYourSaas#317]
## Describe the bug

I have configured my main domain as `firma.com`.mx, but in some places the "admin" url is only `com.mx` instead `myaccount.firma.com.mx` or `firma.com.mx`

![image](https://github.com/DoliCloud/SellYourSaas/assets/30660343/e59c4dad-680a-4a4c-861d-cacce1215fc1)

![image](https://github.com/DoliCloud/SellYourSaas/assets/30660343/a704afa5-52ec-48e6-93aa-655cf081d94d)

![image](https://github.com/DoliCloud/SellYourSaas/assets/30660343/5a38e552-345c-4811-a7d2-9c4f2d69acb9)

### Configure a double sufix domain

1. go to the admin web site `https://admin.firma.com.mx`
2. Click on **Home->Setup->Modules/Application->SELLYOURSAAS** module
3. Into the field **List of Sub-domain to deploy new instances** type firma.com.mx
4. Save the changes.

### Check the changes

1. Acces again to the module SELLYOURSAAS (do not refresh)
2.  Chech the label **Default product/service for instance (suggested for new contract/instance)**

**Expected behavior**

The domain must be firma.com.mx instead com.mx

**Screenshots**

![image](https://github.com/DoliCloud/SellYourSaas/assets/30660343/7152a8c9-acbb-4147-b108-b1fb9e629514)

Image with only one sufix

**SELLYOURSAAS:**
 - Version: 2.1

**Dolibarr:**
 - Version: 18.0.0

**Additional context**

**Comment by erwinpalma** [comment]
## As Workarround

Into the file` /home/admin/wwwroot/dolibarr/htdocs/core/lib/geturl.lib.php` line 345, I have noticed that the $mode == 2 fills the requirements, but the chalenge was to know if there is more than one sufixes.

I have added a validation (of course, probably is not the mort professional code ever developed but it works).

```php
function getDomainFromURL($url, $mode = 0)
{
	$parts = explode('.', $url); 

	foreach ( array_reverse($parts) as $key => $value ) {
		if ($key == 0 and $value == "com") {
			$mode = 1;
		}
		if ($key == 1 and $value == "com") {
			$mode = 2;
		}
	}

	$tmpdomain = preg_replace('/^https?:\/\//i', '', $url); // Remove http(s)://
	$tmpdomain = preg_replace('/\/.*$/i', '', $tmpdomain); // Remove part after domain
	if ($mode == 2) {
		$tmpdomain = preg_replace('/^.*\.([^\.]+)\.([^\.]+)\.([^\.]+)$/', '\1.\2.\3', $tmpdomain); // Remove part 'www.' before 'abc.mydomain.com'
	} else {
		$tmpdomain = preg_replace('/^.*\.([^\.]+)\.([^\.]+)$/', '\1.\2', $tmpdomain); // Remove part 'www.abc.' before 'mydomain.com'
	}
	if (empty($mode)) {
		$tmpdomain = preg_replace('/\.[^\.]+$/', '', $tmpdomain); // Remove first level domain (.com, .net, ...)
	}

	return $tmpdomain;
}

```

**Comment by eldy** [comment]
Don't know if the fix into function getDomainFromURL() that will be available in standard dolibarr is enough. Thanks to reopen if you experience other errors depsite this change.
