### ISSUE TITLE
New instance password doesn't work. Need to reset password.

### ISSUE THREAD

**Issue by infocillasas** [DoliCloud/SellYourSaas#345]
**Describe the bug**
Newly created instance password doesn't work.

**To Reproduce**
1. Login into customer account (myaccount.xxxxx.xxx)
2. Create a new instance/contract with password
3. Connect to the newly created instance ("admin" / password)
4. Password is not the right one and need to reset the password

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser : Brave Browser

**Screenshots**

SellYourSaas module config, inside "Sign in (security/options)" tab
There is no defined algorythm nor salt values

![image](https://github.com/DoliCloud/SellYourSaas/assets/150066394/bb0aeb9f-7793-4363-b4bc-c049099e193a)

Package definition. SQL after deployment. I don't really understand what should be filled here. This is the default setup.

![image](https://github.com/DoliCloud/SellYourSaas/assets/150066394/416e3868-a558-4c13-b294-41010b6251dc)

**Comment by hregis** [comment]
@infocillasas add "password_hash" in algorythm field or use `__APPPASSWORDPASSWORD_HASH__` instead `__APPPASSWORD0SALTED__` in "sql after deployement"

**Comment by infocillasas** [comment]
Thanks @hregis 
I tried both config:
algorythm field empty & __APPPASSWORDPASSWORD_HASH__ in "sql after deployment"
algorythm field with 'password_hash' & __APPPASSWORD0SALTED__ in "sql deployment"

None works

**Comment by sun2dayo** [comment]
Hi
on field **Sql after deployment** Try __APPPASSWORD__

**Comment by sun2dayo** [comment]
__APPPASSWORD__

**Comment by hregis** [comment]
@sun2dayo  `__APPPASSWORD__` is not encrypted !

**Comment by hregis** [comment]
@infocillasas what is the value of the constant MAIN_SECURITY_HASH_ALGO in your dolibarr master ?

**Comment by hregis** [comment]
by default for the fresh install of dolibarr this is "password_hash" and for the "sql deployment" you must use `__APPPASSWORDPASSWORD_HASH__`

**Comment by infocillasas** [comment]
> @infocillasas what is the value of the constant MAIN_SECURITY_HASH_ALGO in your dolibarr master ?

@hregis it is password_hash

**Comment by hregis** [comment]
@infocillasas if algorythm field is empty, `MAIN_SECURITY_HASH_ALGO`  is used (password_hash)

**Comment by hregis** [comment]
@infocillasas my "sql after deployment"

`UPDATE __INSTANCEDBPREFIX__user set pass_crypted = '__APPPASSWORD0SALTED__', email = '__APPEMAIL__', datec = NOW() WHERE login = 'admin';`

**Comment by hregis** [comment]
try : 

UPDATE __INSTANCEDBPREFIX__user set pass_crypted = '__APPPASSWORDPASSWORD_HASH__', email = '__APPEMAIL__', datec = NOW() WHERE login = 'admin';

**Comment by infocillasas** [comment]
> @infocillasas if algorythm field is empty this is password_hash by default

@hregis: algorythm field is empty and I've put "pass_crypted = '__APPPASSWORDPASSWORD_HASH__'" in Package config, in "sql after deployment" section. However, the password is not the correct one (in the db the value is ```$2y$10$fK/m37ymZ4XCdZGKqZaBsOoMQdzaTrFo3./6MCaSweDRCwerbgi0G``` which looks like a password_hash profile)

When I reset the password on the same instance, and put agin the same initial password string, I get something like ```f05aff0ca321af16041e4a2810719367```which seems to indicate that password_hash is not used to calculate the pass_crypted db field.

Could you help please, i don't understand how to configure this part without restting the password (which would be a pain for customers...)

My Master & Deployments Dolibarr are v18.0.5

**Comment by hregis** [comment]
@infocillasas `f05aff0ca321af16041e4a2810719367` this is md5 !

**Comment by hregis** [comment]
@infocillasas what is the value of MAIN_SECURITY_HASH_ALGO in your sql dump for new install ?

**Comment by hregis** [comment]
@infocillasas have you a value for MAIN_SECURITY_SALT in your sql dump ? if yes try to remove this value

**Comment by infocillasas** [comment]
> UPDATE __INSTANCEDBPREFIX__user set pass_crypted = '__APPPASSWORDPASSWORD_HASH__', email = '__APPEMAIL__', datec = NOW() WHERE login = 'admin';

@hregis unfortunately it doesn't work

**Comment by infocillasas** [comment]
> @infocillasas have you a value for MAIN_SECURITY_SALT in your sql dump ? if yes try to remove this value

@hregis: I removed the MAIN_SECURITY_SALT value and put "NULL" instead. But it still doesn't work...

**Comment by infocillasas** [comment]
@hregis : it finally worked with your setup --> ```pass_crypted = '__APPPASSWORD0SALTED__'```, algorythm field empty, and MAIN_SECURITY_SALT value in sql dump removed (that last parameter was the blocking one)

Thanks a lot for your help !!
