### ISSUE TITLE
Adding Option to a Service

### ISSUE THREAD

**Issue by infocillasas** [DoliCloud/SellYourSaas#348]
**Describe the bug**
Try to add Extra Gigabyte Option in a Dolibarr Service, but there is no Virtual Package available in the Service page as recommanded in the documentation.

**Expected behavior**
Be able to add extra Gigabytes in the invoicing process, as described in the doc (https://github.com/DoliCloud/SellYourSaas/blob/master/doc/Documentation%20SellYourSaas%20-%20Master%20and%20Deployment%20Servers%20-%20EN.asciidoc#setup-of-services)
> Note: Options and Metrics type services must be attached to an Application type service from the Virtual Products tab

**Screenshots**
![SyS-Extra-Gigabyte](https://github.com/DoliCloud/SellYourSaas/assets/150066394/2608c9d6-f091-4005-a4bb-e1437edc03aa)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by infocillasas** [comment]
Update: looks like Options (like extra Gb) need to be added as System service (and not Option) in a kit (and not in Virtual Product)

**Comment by eldy** [comment]
Also i discovered a bug recently with option (the code was sometime deploying the application before the option, and it should). Fixes were done in commits:
cfea9df52ab7d8078a690b604a702564fe473ea3
a21d76b5ca3f44eb1e604c9f682c21a73cc9b1e2
abe7569f05dfbb0b628c9606e0f3d2499b250475
Don't know if it was the trouble, but this is another possible reason.

**Comment by infocillasas** [comment]
Thanks @eldy for the update.
I still cannot add extra Gb as a System Service into a kit.
The extra Gb is still appearing in the invoice with the quantity "1", whereas I put a BASH command in the quantity calculation of this extra Gb service.

**Comment by eldy** [comment]
This is the setup i have on my production

![Screenshot_20240415_171124_DoliDroid.jpg](https://github.com/DoliCloud/SellYourSaas/assets/883887/dfb12787-5d73-409f-bc09-d809863edd9c)

**Comment by infocillasas** [comment]
Ok, great, thank you @eldy I'll try that

**Comment by infocillasas** [comment]
> duc is used instead of du so this need no IO to get result. Calculation is done during the backup by running duc (but because backup has already read all files, the cache make the ducs command immediate).

I fully understand that and this is a great design.
What if I don't use the included backup feature in SellyourSaas ? What triggers the "refresh" of the quantity (for extra Gb for example) and is it somehow dependant of the backup feature ? In other terms, how to trigger "refresh" process without using the backup feature ?

**Comment by eldy** [comment]
> > duc is used instead of du so this need no IO to get result. Calculation is done during the backup by running duc (but because backup has already read all files, the cache make the ducs command immediate).
> 
> I fully understand that and this is a great design.
> What if I don't use the included backup feature in SellyourSaas ? What triggers the "refresh" of the quantity (for extra Gb for example) and is it somehow dependant of the backup feature ? In other terms, how to trigger "refresh" process without using the backup feature ?

The backup trigger the run of ducs to calculate space used and save it into a .ducs file 
The refresh is the process to update the qty. It is run 24h before before generating a new invoice to update qty in contract and recurring invoice.
There is no relation between refresh and backup. I just choose to define a system metric that reuse the content of .ducs file to return the value to use in qty.
But you can use any bash command that will return the value of your choice

**Comment by infocillasas** [comment]
Thanks @eldy for the feedback, I'll look into it

**Comment by sun2dayo** [comment]
Hi. in the help provided in the application suggests using "BASH" in uppercase, but this causes an error. However, replacing "BASH" with "bash" in lowercase resolves the problem.

It seems there is a case sensitivity issue in the way the application handles shell commands. Since Unix/Linux systems are case-sensitive, the executable for Bash is typically named "bash" in lowercase. Using "BASH" in uppercase likely results in the system failing to locate the correct shel
