### ISSUE TITLE
fk_user_modif field missing in table llx_sellyoursaaas_deployementserver

### ISSUE THREAD

**Issue by Movix** [DoliCloud/SellYourSaas#355]
calling link
https://admin.sellyouersaas.com/custom/sellyoursaas/deploymentserver_list.php
ran into an error
```
Requête dernier accès en base en erreur: SELECT t.rowid,t.ref,t.fromdomainname,t.servercountries,t.ipaddress,t.status,t.servercustomerannounce,t.servercustomerannouncestatus,t.serversignaturekey,t.note_private,t.note_public,t.date_creation,t.date_modification,t.fk_user_modif FROM llx_sellyoursaas_deploymentserver as t WHERE 1 = 1 ORDER BY t.rowid ASC LIMIT 21
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 't.fk_user_modif' in 'field list'
```

I added the missing field manually in the table and it seem to work

**Comment by eldy** [comment]
Into the file sql/dolibarr_allversions.sql you should find the instruction to migrate to last version of sellyoursaas. You shoudl get:
ALTER TABLE llx_sellyoursaas_deploymentserver ADD COLUMN fk_user_modif integer;
ALTER TABLE llx_sellyoursaas_deploymentserver ADD COLUMN note_public text;
ALTER TABLE llx_sellyoursaas_deploymentserver ADD COLUMN serversignaturekey varchar(128);
