### ISSUE TITLE
on customer register page subdomain list is empty

### ISSUE THREAD

**Issue by Movix** [DoliCloud/SellYourSaas#356]
when connecting the customer registration page the form cannot be completed because the sub domain dropdown is empty.

Perhaps it's a installation error i have done or some missing or wrong parameters in the sellyoursaas inteface that i have done for the deployement server or the package.

The error related was a incorrect SQL query with a statement ending in the where clause with 'AND (())

The solution i found to work around this issue was to edit the file 
/home/admin/wwwroot/dolibarr_sellyoursaas/class/deploymentserver.class.php at line 409 by commenting out
`//$sql .= forgeSQLFromUniversalSearchCriteria($filter, $errormessage);`

**Comment by eldy** [comment]
What was your dolibarr version ?

**Comment by Movix** [comment]
Hello Laurent,

It was 19.0.0



De : Laurent Destailleur ***@***.***>
Envoyé : samedi 13 avril 2024 19:00
À : DoliCloud/SellYourSaas ***@***.***>
Cc : Spam ***@***.***>; Author ***@***.***>
Objet : Re: [DoliCloud/SellYourSaas] on customer register page subdomain list is empty (Issue #356)


What was your dolibarr version ?

**Comment by eldy** [comment]
Can you intercept the value of $filter just before the call of forgeSQLFromUniversalSearchCriteria()  ?

**Comment by Movix** [comment]
Hello Laurent,

It seems to be an empty string

Movix

De : Laurent Destailleur ***@***.***>
Envoyé : samedi 13 avril 2024 19:41
À : DoliCloud/SellYourSaas ***@***.***>
Cc : Spam ***@***.***>; Author ***@***.***>
Objet : Re: [DoliCloud/SellYourSaas] on customer register page subdomain list is empty (Issue #356)


Can you intercept the value of $filter just before the call of forgeSQLFromUniversalSearchCriteria() ?

**Comment by eldy** [comment]
I think problem has been fixed in Dolibarr develop. Because we have now
```
	if ($filter === '') {
		return '';
	}
```
at begin of 
`forgeSQLFromUniversalSearchCriteria()`

**Comment by Movix** [comment]
Modified like suggested. Works. Thank you
